text:text.cc bundle.cpp
	g++ -g -o text text.cc bundle.cpp -lstdc++fs -lpthread -ljsoncpp -std=c++11
	# g++ -o text text.cc bundle.cpp -lstdc++fs -lpthread -ljsoncpp -std=c++11

.PHONY:clean
clean:
	rm -rf text